# Generated by Django 4.2 on 2023-04-30 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Queue', 'Queue'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Queue', max_length=50)),
                ('booking_datetime', models.DateTimeField()),
                ('service', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('notify_datetime', models.DateTimeField()),
                ('short_desc', models.TextField()),
                ('type', models.CharField(choices=[('Danger', 'danger'), ('Warning', 'warning'), ('Info', 'info'), ('Success', 'success')], max_length=100)),
                ('booking_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.bookingrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
