# Generated by Django 4.2 on 2023-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salon",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
