# Generated by Django 4.2 on 2023-05-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salon_location_alter_salon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservice',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='salon.salon'),
        ),
    ]
